export const BLOG_CATEGORY = {
    FASHION_TRENDS: "FASHION_TRENDS",
    STYLING_GUIDES: "STYLING_GUIDES",
    BUYING_GUIDES: "BUYING_GUIDES",
    MEN_FASHION: "MEN_FASHION",
    WOMEN_FASHION: "WOMEN_FASHION",
    KIDS_FASHION: "KIDS_FASHION",
    SEASONAL_COLLECTIONS: "SEASONAL_COLLECTIONS",
    STREETWEAR: "STREETWEAR",
    FABRIC_GUIDES: "FABRIC_GUIDES",
    CLOTHING_CARE: "CLOTHING_CARE",
    NEW_ARRIVALS: "NEW_ARRIVALS",
    BRAND_STORIES: "BRAND_STORIES",
} as const;